{{- if and .Values.ingress.enable .Values.ingress.acme }}
{{- $root := . }}
{{- $httpLocation := .Values.ingress.path }}
{{- $apiVersion := include "apiVersions.ingress" $ }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $root }}-acme"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
{{- range $host := .Values.ingress.acme.hosts }}
    - {{ $host | quote }}
{{- end }}
    secretName: "{{ template "anycableGo.fullname" $root }}-tls-acme"
  rules:
{{- range $host := .Values.ingress.acme.hosts }}
{{- $serviceName := include "anycableGo.fullname" $root }}
  - host: {{ $host | quote }}
    http:
      paths:
        {{- if eq $apiVersion "networking.k8s.io/v1" }}
        - path: {{ $httpLocation | quote }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $serviceName | quote }}
              port:
                number: 80
        {{- else }}
        - path: {{ $httpLocation | quote }}
          backend:
            serviceName: {{ $serviceName | quote }}
            servicePort: 80
        {{- end }}
{{- end }}
{{- end }}
