{{- $values := include "anycableGo.values" . | fromYaml }}
{{- with $values }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "anycableGo.fullname" $ }}
  labels:
    app: {{ template "anycableGo.name" $ }}
    component: anycable-go
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .replicas | default 2 }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      app: {{ template "anycableGo.name" $ }}
      component: anycable-go
      release: {{ $.Release.Name | quote }}
  strategy:
    {{- with (.rollingUpdate | default dict) }}
    rollingUpdate:
      maxSurge: {{ .maxSurge | default 1 }}
      maxUnavailable: {{ .maxUnavailable | default 1 }}
    type: RollingUpdate
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "anycableGo.name" $ }}
        component: anycable-go
        chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
        release: {{ $.Release.Name | quote }}
        heritage: {{ $.Release.Service | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-secret.yml") $ | sha256sum }}
      name: {{ $.Release.Name | quote }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector: {{ toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: {{ template "anycableGo.name" $ }}
                    release: {{ $.Release.Name | quote }}
              weight: 100
      {{- if .image.pullSecrets.enabled }}
      imagePullSecrets:
        - name: "{{ $.Release.Name }}-docker-registry-secret"
      {{- end }}
      containers:
        - name: anycable-go
          {{- with .env }}
          ports:
            - name: http
              containerPort: {{ .anycablePort | required "A valid listening port for anycable is required! Please specify `env.anycablePort` in values!" }}
              protocol: TCP
            {{- if .anycableMetricsPort }}
            - name: metrics
              containerPort: {{ .anycableMetricsPort }}
              protocol: TCP
            {{- end }}
          env:
            {{- if .anycableHost }}
            - name: ANYCABLE_HOST
              value: {{ .anycableHost | quote }}
            {{- end }}
            - name: ANYCABLE_PORT
              value: {{ .anycablePort | quote }}
            {{- if .anycablePath }}
            - name: ANYCABLE_PATH
              value: {{ .anycablePath | quote }}
            {{- end }}
            {{- if .tls }}
            - name: ANYCABLE_SSL_CERT
              value: /etc/ssl/anycable-go/tls.crt
            - name: ANYCABLE_SSL_KEY
              value: /etc/ssl/anycable-go/tls.key
            {{- end }}
            {{- if .anycableRedisChannel }}
            - name: ANYCABLE_REDIS_CHANNEL
              value: {{ .anycableRedisChannel | quote }}
            {{- end }}
            {{- if .anycableRedisSentinelDiscoveryInterval }}
            - name: ANYCABLE_REDIS_SENTINEL_DISCOVERY_INTERVAL
              value: {{ .anycableRedisSentinelDiscoveryInterval | quote }}
            {{- end }}
            {{- if .anycableRedisKeepaliveInterval }}
            - name: ANYCABLE_REDIS_KEEPALIVE_INTERVAL
              value: {{ .anycableRedisKeepaliveInterval | quote }}
            {{- end }}
            {{- if .anycableRpcHost }}
            - name: ANYCABLE_RPC_HOST
              value: {{ .anycableRpcHost | quote }}
            {{- end }}
            {{- if .anycableHeaders }}
            - name: ANYCABLE_HEADERS
              value: {{ .anycableHeaders | quote }}
            {{- end }}
            {{- if .anycableDisconnectRate }}
            - name: ANYCABLE_DISCONNECT_RATE
              value: {{ .anycableDisconnectRate | quote }}
            {{- end }}
            {{- if .anycableLogLevel }}
            - name: ANYCABLE_LOG_LEVEL
              value: {{ .anycableLogLevel | quote }}
            {{- end }}
            {{- if .anycableLogFormat }}
            - name: ANYCABLE_LOG_FORMAT
              value: {{ .anycableLogFormat | quote }}
            {{- end }}
            {{- if .anycableDebug }}
            - name: ANYCABLE_DEBUG
              value: {{ .anycableDebug | quote }}
            {{- end }}
            {{- if .anycableMetricsLog }}
            - name: ANYCABLE_METRICS_LOG
              value: {{ .anycableMetricsLog | quote }}
            {{- end }}
            {{- if .anycableMetricsLogInterval }}
            - name: ANYCABLE_METRICS_LOG_INTERVAL
              value: {{ .anycableMetricsLogInterval | quote }}
            {{- end }}
            {{- if .anycableMetricsLogFormatter }}
            - name: ANYCABLE_METRICS_LOG_FORMATTER
              value: {{ .anycableMetricsLogFormatter | quote }}
            {{- end }}
            {{- if .anycableMetricsHttp }}
            - name: ANYCABLE_METRICS_HTTP
              value: {{ .anycableMetricsHttp | quote }}
            {{- end }}
            {{- if .anycableMetricsHost }}
            - name: ANYCABLE_METRICS_HOST
              value: {{ .anycableMetricsHost | quote }}
            {{- end }}
            {{- if .anycableMetricsPort }}
            - name: ANYCABLE_METRICS_PORT
              value: {{ .anycableMetricsPort | quote }}
            {{- end }}
            {{- if .anycableHealthPath }}
            - name: ANYCABLE_HEALTH_PATH
              value: {{ .anycableHealthPath | quote }}
            {{- end }}
            {{- if .anycableMaxMessageSize }}
            - name: ANYCABLE_MAX_MESSAGE_SIZE
              value: {{ .anycableMaxMessageSize | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: "{{ template "anycableGo.fullname" $ }}-secrets"
            {{- range $name := .secrets }}
            - secretRef:
                name: {{ $name | quote }}
            {{- end }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | quote }}
          {{- if hasKey $values "livenessProbe" }}
          livenessProbe: {{ toYaml .livenessProbe | nindent 12 }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: {{ if .tls }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 90
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          {{- end }}
          {{- if hasKey $values "readinessProbe" }}
          readinessProbe: {{ toYaml .readinessProbe | nindent 12 }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: {{ if .tls }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          {{- end }}
          {{- if .resources }}
          resources: {{ toYaml .resources | nindent 12 }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .tls }}
          volumeMounts:
            - name: ssl
              mountPath: "/etc/ssl/anycable-go"
              readOnly: true
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- if .tls }}
      volumes:
        - name: ssl
          secret:
            secretName: {{ .tls.secretName | quote }}
      {{- end }}
{{- end }}
