{{- if and .Values.ingress.enable .Values.ingress.nonAcme.hosts }}
{{- $root := . }}
{{- $httpLocation := .Values.ingress.path }}
{{- $apiVersion := include "apiVersions.ingress" $ }}
---
apiVersion: {{- $apiVersion }}
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $root }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
{{- range $secret := .Values.ingress.nonAcme.hosts }}
  - hosts:
{{- range $host := $secret.names }}
    - {{ $host | quote }}
{{- end }}
    secretName: {{ $secret.secretName | quote }}
{{- end }}
  rules:
{{- range $secret := .Values.ingress.nonAcme.hosts }}
{{- range $host := $secret.names }}
{{- $serviceName := include "anycableGo.fullname" $root }}
  - host: {{ $host | quote }}
    http:
      paths:
        {{- if eq $apiVersion "networking.k8s.io/v1" }}
        - path: {{ $httpLocation | quote }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $serviceName | quote }}
              port:
                number: 80
        {{- else }}
        - path: {{ $httpLocation | quote }}
          backend:
            serviceName: {{ $serviceName | quote }}
            servicePort: 80
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
