{{- $apiVersion := include "anycableGo.apiVersions.ingress" $ }}
{{- with .Values.ingress }}
{{- if ($apiVersion | and .enable | and .nonAcme.hosts) }}
---
apiVersion: "{{ $apiVersion }}"
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $ }}"
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
{{- range $secret := .nonAcme.hosts }}
  - hosts:
{{- range $host := $secret.names }}
    - {{ $host | quote }}
{{- end }}
    secretName: {{ $secret.secretName | quote }}
{{- end }}
{{- if (first .nonAcme.hosts | and (first .nonAcme.hosts).names) }}
  rules:
{{- range $secret := .nonAcme.hosts }}
{{- range $host := $secret.names }}
{{- $serviceName := include "anycableGo.fullname" $ }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: {{ .path | quote }}
          {{- if eq $apiVersion "networking.k8s.io/v1" }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $serviceName | quote }}
              port:
                number: 80
          {{- else }}
          backend:
            serviceName: {{ $serviceName | quote }}
            servicePort: 80
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
